// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLes01R2b575Ai9PWpv9Uqy66hCRJWFys',
    appId: '1:119046393072:web:46797ab8207cdb93768635',
    messagingSenderId: '119046393072',
    projectId: 'babymeal',
    authDomain: 'babymeal-bafb5.firebaseapp.com',
    storageBucket: 'babymeal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINMg_h8NcVZkF0dJHGOmOGkN-xVQSimk',
    appId: '1:119046393072:android:fcb39f3e24570f4a768635',
    messagingSenderId: '119046393072',
    projectId: 'babymeal',
    storageBucket: 'babymeal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9RG8sJkYKt2JP4V5K3VjVAZm5WkrVcl0',
    appId: '1:119046393072:ios:95f3ac995c3cc5da768635',
    messagingSenderId: '119046393072',
    projectId: 'babymeal',
    storageBucket: 'babymeal.appspot.com',
    iosBundleId: 'com.example.babymeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9RG8sJkYKt2JP4V5K3VjVAZm5WkrVcl0',
    appId: '1:119046393072:ios:113e12cbe03b352a768635',
    messagingSenderId: '119046393072',
    projectId: 'babymeal',
    storageBucket: 'babymeal.appspot.com',
    iosBundleId: 'com.example.babymeal.RunnerTests',
  );
}
