name: babymeal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-131.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  material: ^1.0.0+2
  card_swiper: ^3.0.0
  easy_rich_text: "^2.0.0"
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio: ^4.0.6
  http: ^0.13.6
  http_parser: ^4.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
  assets:
    - assets/images/
    - assets/images/meal.png
    - assets/images/dessert.png
    - assets/images/community.png
    - assets/images/community_sel.png
    - assets/images/my.png
    - assets/images/my_sel.png
    - assets/images/recommend.png
    - assets/images/recommend_sel.png
    - assets/images/scrab.png
    - assets/images/scrab_sel.png
    - assets/images/refrigerator.png
    - assets/images/refrigerator_sel.png
    - assets/images/bread.png
    - assets/images/onion.png
    - assets/images/fish.png
    - assets/images/egg.png
    - assets/images/cheese.png
    - assets/images/broccoli.png
    - assets/images/scrab_empty.png
    - assets/images/scrab_full.png
    - assets/images/rectangle.png
    - assets/images/google.png
